### ISSUE TITLE
bundle.js loaded from public/bundle.js, not loaded from webpack-dev-server, in development

### ISSUE THREAD

**Issue by bdefore** [fredguest/rails-api-react-demo-finished#1] opened 2015-03-11 01:41 UTC
Perhaps I missed a step in your instructions, but I'm unable to see my changes reflected when editing .jsx files.

I've cloned the repo, run bundle install, npm install (which generates a public/bundle.js). I noticed that config/environments/development-example.rb is in your starter repo but not in the finished one. Perhaps that should be in here too?

I copied over config/environments/development-example.rb to config/environments/development.rb and then added five environment variables filled out.

```
  ENV['SECRET_KEY_BASE'] = '{MY_SECRET_KEY_BASE}'
  ENV['TWITTER_CONSUMER_KEY'] = '{MY_KEY}'
  ENV['TWITTER_CONSUMER_SECRET'] = '{MY_SECRET}'
  ENV['ORIGIN'] = 'http://localhost:8080'
  ENV['OAUTH_CALLBACK'] = 'http://127.0.0.1:3000/access_token'
```

I can now run ```rails s -b 127.0.0.1``` in one terminal window and ```npm run devserve``` in another and I am able to open localhost:3000 and authenticate fine with twitter and add blabs.

Unfortunately, I think I missed a step because I'm not seeing my jsx changes reflected and I'm wondering if our routes are setup correctly in Rails. If I edit a jsx file, I can see webpack log out that it is rebuilding. The public/bundle.js file is unchanged. This is to be expected since we shouldn't be using that file anyway. But if I delete that file and return to localhost:3000, the page doesn't render. It makes a request for bundle.js and gets what looks like index.html for a response, and tries to execute that HTML as JavaScript. It's as if it's not routing correctly to the webpack dev server. If I go to localhost:8080 I can see the page rendering with my latest updates. If I run ```npm run devbuild``` it generates public/bundle.js and I can load the page, but I'd rather not run that manually each time.

Did I miss something?

**Comment by bdefore** [comment] 2015-03-11 01:46
As a workaround, I am able to add --watch to the devbuild task in package.json, and run ```npm run devbuild``` (for bundle.js rebuilds) and with ```npm run devserve``` (for auth callbacks) and it works fine, although it's redundantly building with each save.

**Comment by fredguest** [comment] 2015-03-11 02:00
I think the mixup is here: "I can now run rails s -b 127.0.0.1 in one terminal window and npm run devserve in another and I am able to open localhost:3000 and authenticate fine with twitter and add blabs." You started the servers correctly but the idea is to visit localhost:8080 after that not localhost:3000. The "npm run devserve" serves the React application to localhost:8080, so that's the location you need to visit in order to see any saved changes to your .jsx files.

If you run "npm run dev**build**" instead of "npm run dev**serve**" then you will get a static build of bundle.js in the public directory and then you'll be able to visit localhost:3000, but because that's using a statically built version of your React app, if you make changes to your .jsx files you will not see them rendered, unless you manualy rerun "npm run devbuild" to rebuild the bundle.js file.

When you say: "But if I delete that file (bundle.js) and return to localhost:3000, the page doesn't render.", that is expected behavior. If you delete the bundle.js file you are deleting your React app, so visiting localhost:3000 should render nothing. Does that make sense?

**Comment by bdefore** [comment] 2015-03-11 06:55
Yes, that makes sense now. Looking down the microscope the wrong end there. If I hit up localhost:8080 it all works as expected. Thanks!

**Comment by fredguest** [comment] 2015-03-11 07:03
nice! no prob. ya it's very easy to mixup on the first run through. glad it's sorted, will close this now.

**Closed** 2015-03-11 07:04 UTC
